mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

'''
当有人从网站请求一个页面 - 例如“/ polls / 34 /”时，
1.Django将加载mysite.urls模块，因为ROOT_URLCONF设置指向它。
2.它找到mysite.urls中的变量urlpatterns，并按顺序遍历正则表达式。
3.找到匹配后'^polls/'，它将剥离匹配的文本（"polls/"），并将剩余的文本发送"34/"到“polls.urls”URLconf进行进一步处理。
4.它找到polls.urls中的变量urlpatterns，再匹配r'^(?P<question_id>[0-9]+)/$'，找到参数views.detail进行进一步处理。
5.找到views.py文件，从中找到detail函数，进行视图渲染并返回。
'''
urlpatterns = [
    url(r'^polls/', include('polls.urls')),  # url()的两个参数，第一个是客户端请求，相当于Servlet，第二个是include函数，它的参数是映射的文件。
    url(r'^admin/', admin.site.urls),  # url()的两个参数，第一个是客户端请求，相当于Servlet，第二个是视图的函数（一般包含在py文件中）
]
# 该include()函数允许引用其他URLconfs。include()使即插即用的URL变得容易。

# 何时使用 include(),当包含其他网址格式时，应始终使用。 admin.site.urls是唯一的例外。

polls/urls.py
# urls.py 就是一个映射文件，它包含一个或多个映射。
#
# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# ]
from django.conf.urls import url
from django.contrib import admin

from . import views

# 现在这个项目只有一个polls应用程序，而在真正的项目中，可能会有多个应用程序，那么Django如何区分他们的URL名称（即name属性值）。
# 最好的做法是，为URLconf添加命名空间。在polls/urls.py文件中，添加一个app_name的属性，进行赋值，设置应用程序的命名空间，用来区分不同的应用程序。
# 需哟注意的是，如果有的模版使用了name作链接，那么这些链接就需要更改，在name前加上app_name:。

app_name = 'polls'
'''
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # url()的三个参数，第一个是客户端请求，相当于Servlet，第二个是视图的函数（一般包含在py文件中），views就是py文件，index是函数。
    # 第三个是命名关键字参数，name。可从Django其他地方明确地引用它，特别是在模板中。

    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # (?P<question_id>[0-9]+)，解析这句代码：
    # ?P<question_id>定义一个参数名为question_id的参数。
    # [0-9]+是用于匹配数字序列（即数字）的正则表达式。
    # 因此，这句代码获取了一个 question_id = [0-9]+ 的参数，

    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]
'''

# 在开发时，我们注意到有一部分页面是相似的，有些代码也是相似的（或者说相同的），这时我们需要用到一个新的技术：通用视图。
'''
只需要采取几个步骤进行转换
1.转换URLconf。（修改polls/urls.py文件）
2.删除一些旧的，不需要的视图。（修改polls/views.py文件）
3.替换成基于Django通用视图的新视图。
'''
# 这里修改了 index ， detail ， result 三个URL ，vote 作为参照不修改。
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^$', admin.site.urls),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'templates/polls/add/$', views.addView.as_view(), name='add'),
    url(r'templates/polls/question/$', views.questionView.as_view(), name='question'),
]

polls/models.py
# 创建模型，相当于Java中的类。有自己的名称和属性。同时也是数据库布局。
import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone

'''
每个模型都由一个类来表示django.db.models.Model。每个模型都有一些类变量，每个变量都表示模型中的数据库字段。

每个字段由Field 类的实例表示- 例如，CharField用于字符字段和 DateTimeField数据时间。这告诉Django每个字段拥有什么类型的数据。
每个Field实例的名称（例如 question_text或pub_date）是字段的名称。将在Python代码中使用此值，数据库将使用它作为列名。
您可以使用可选的第一个位置参数来 Field指定人类可读的名称。这用于Django的几个内省部分，它可以作为文档。
如果未提供此字段，Django将使用机器可读的名称。
在这个例子中，我们只定义了一个可读的名字Question.pub_date。对于此模型中的所有其他字段，该字段的机器可读名称将足以作为其可读的名称。

一些Field类有必要的参数。 CharField例如，要求你给它一个 max_length。这不仅在数据库模式中使用，而且可用于验证。
A Field也可以有各种可选参数; 在这种情况下，我们将default值 设置votes为0。
最后，注意一个关系的定义，使用 ForeignKey。这告诉Django每个Choice都与一个相关Question。Django支持所有常见的数据库关系：多对一，多对多和一一对应。
'''


@python_2_unicode_compatible  # only if you need to support Python 2
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')  # 日期类型数据，并定义'date published'作为人类可读的名称。

    def __str__(self):
        # 为模型添加__str__()方法非常重要，这不仅在处理交互式提示时方便您使用，还能让管理员通过直观但表示更好但管理Django。
        # 当在shell窗口下调用Question.objects.all()时，会打印所有的Question，其实调用的就是__str__方法，生成一个Set并返回。
        return self.question_text

    '''
    def was_published_recently(self): #一个自定义的方法，用于测试
        # 这个方法的目的是，判断一个Question实例是不是最近发布的。方法： 发布时间 >= 当前时间 -1
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    '''

    # 我们发现这个方法有缺陷，现在对它进行改进，同时，该方法可以定义虚拟字段
    def was_published_recently(self):
        now = timezone.now()
        # 更改后的方法：昨天<=当前时间<=明天
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # 对was_published_recently方法显示的内容进行定义：boolean属性指定该字段显示为图表，short_description列标题显示内容，admin_order_field排序字段
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


@python_2_unicode_compatible  # only if you need to support Python 2
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)  # 设置外健
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


'''
这些模型代码给了Django很多信息。有了它，Django能够：
    1.为此应用程序创建数据库模式（语句）。CREATE TABLE。
    2.创建用于访问Question和Choice对象的Python数据库访问API 。
但首先我们需要告诉我们的项目该polls应用是安装的。
另外，Django应用程序（如polls就是一个应用程序）是“可插拔”：您可以在多个项目中使用应用程序，您可以分发应用程序，因为它们不必与给定的Django安装绑定。

那么如何在项目中使用这个应用程序呢？
要将该应用程序包括在我们的项目中，我们需要在设置中添加对其配置类的引用INSTALLED_APPS。
polls的PollsConfig配置在polls/apps.py文件中，所以它的虚线路径'polls.apps.PollsConfig'。
编辑mysite/settings.py文件，并将该虚线路径添加到该INSTALLED_APPS设置。

然后，我们需要应用这些更改到数据库中。

总体来说，分三步：
改变你的模型（in models.py）。
运行以创建这些更改的迁移。python manage.py makemigrations polls
运行以将这些更改应用于数据库。python manage.py migrate
'''
'''
接下来，我们尝试着使用Python shell，使用这个python manage.py shell命令。
我们使用这个，而不是简单地输入“python”，
因为manage.py 设置了DJANGO_SETTINGS_MODULE环境变量，这为Django提供了你的mysite/settings.py文件里的Python路径。

进入Shell编程。
然后，在命令行窗口下探索数据库API。
键入命令 from polls.models import Question,Choice ＃导入我们刚写的模型类。
键入命令 Question.objects.all() ＃查看所有的Question
    与这个命令相似的命令：
        Question.objects.filter(id=1)    # 查询 id = 1 的Question
        Question.objects.filter(question_text__startswith='What') # 查询以'What'开头的question_text的Question。
        Question.objects.get(pub_date__year=current_year) # 获取pub_date的year等于current_year（变量，需自己设置）的Question。
        Question.objects.get(id=1) # 获取 id = 1 的Question，它与外健获取Question.objects.get(pk=1)是相等的。

键入命令 from  django.utils  import  timezone
在默认设置文件中启用对时区的支持，所以Django需要一个tzinfo的datetime为pub_date。使用timezone.now（）。

键入命令 q = Question(question_text="What's new?", pub_date=timezone.now()) #生成一个Question实例
键入命令 q.save() #保存q到数据库中，必须显式调用save（）。
    可以直接查看q的属性，如q.question_text，也可以直接更改q.question_text = "为什么"，但更改后要记住保存：q.save() 。
    
如何创建Choice？？
首先，我们知道Choice的外健是Question的主键。
所以
1.先获取一个Question实例，q = Question.objects.get(id=1)。
2.通过q.choice_set.create(choice_text='Just hacking again', votes=0)进行创建。不需要调用save()方法。
当然，也可以写成 c = q.choice_set.create(choice_text='Just hacking again', votes=0)，把结果保存在变量c中。

键入命令 c = q.choice_set.filter(choice_text__startswith='Just hacking') #获取一个Choice实例。
键入命令 c.delete() #可以在数据库里删除这条记录。
'''

'''
退出Shell编程。
我们尝试着创建一个超级管理员。
键入命令 python manage.py createsuperuser，然后根据命令输入即可。
现在，为们可以登录管理员页面了。http://127.0.0.1:8000/admin/。

注意事项：

1.表单是从Question模型自动生成的。
2.不同的模型字段类型（DateTimeField， CharField）对应于适当的HTML输入小部件。每种类型的字段知道如何在Django管理员中显示自己。
3.每个都DateTimeField获得免费的JavaScript快捷方式。
日期获取“Today”快捷方式和日历弹出窗口，并且时间获取“Now”快捷方式和一个方便的弹出窗口，列出常用的时间。
'''

'''
-- Create model Choice
--
CREATE TABLE "polls_choice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "choice_text" varchar(200) NOT NULL, "votes" integer NOT NULL);
--
-- Create model Question
--
CREATE TABLE "polls_question" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "question_text" varchar(200) NOT NULL, "pub_date" datetime NOT NULL);
--
-- Add field question to choice
--
ALTER TABLE "polls_choice" RENAME TO "polls_choice__old";
CREATE TABLE "polls_choice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "choice_text" varchar(200) NOT NULL, "votes" integer NOT NULL, "question_id" integer NOT NULL REFERENCES "polls_question" ("id"));
INSERT INTO "polls_choice" ("id", "choice_text", "votes", "question_id") SELECT "id", "choice_text", "votes", NULL FROM "polls_choice__old";
DROP TABLE "polls_choice__old";
CREATE INDEX "polls_choice_question_id_c5b4b260" ON "polls_choice" ("question_id");
COMMIT;
'''

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.http import Http404
from django.template import loader
from django.urls import reverse
from .models import Choice, Question
from django.views import generic
from django.utils import timezone


# 这是一个视图，它需要一个映射。
# def index(request):
#   return HttpResponse("Hello, world. You're at the polls index.")

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     output = ', '.join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)

# def index(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    template = loader.get_template('polls/index.html')  # 加载模版
#    context = {
#        'latest_question_list': latest_question_list,
#    }
#    return HttpResponse(template.render(context, request))  # 用template.render方法渲染


# 除了用template.render方法渲染，Django还提供了一个快捷的渲染方法。当用了这种方法，就会发现，不需要导入loader和HttpResponse了。
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}  # context，dict类型的参数。
    return render(request, 'polls/index.html', context)
    # 用render()函数渲染，将请求对象作为其第一个参数，模板作为其第二个参数，第三个参数可选(事实上，第三个参数名不固定，但用context这个变量名是习惯)。
    # 它返回HttpResponse 给定上下文渲染的给定模板的对象。


# 接下来我们添加多个视图，当然，他们需要各自不同的映射。
# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)

# def detail(request, question_id):
#     try:
#        question = Question.objects.get(pk=question_id) # pk也行id 也行，都是数据库的操作。
#     except Question.DoesNotExist:   # 如果发生请求的ID不存在的问题，则该视图引发异常.
#         raise Http404("Question does not exist")
#     return render(request, 'polls/detail.html', {'question': question})

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    # 当然，也可以用更简单的get_object_or_404方法抛出异常。这个方法第一个参数是Django模型，然后是任意数量的关键字参数。
    return render(request, 'polls/detail.html', {'question': question})


# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        '''
        #request.POST是一个类似字典的对象（dict），可通过键名访问提交的数据。
        #request.POST['choice']，即 以选择的选项name作为键，获取对应的值。
        
        #请注意，Django还提供request.GET以相同的方式访问GET数据。但是我们request.POST在代码中明确使用，以确保仅通过POST调用更改数据。
        '''
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "你没有进行选择",
        })
    else:
        selected_choice.votes += 1  # 加1
        selected_choice.save()  # 然后保存
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        # 重定向。reverse函数，第一个参数是 视图的name值，第二个参数指定了args参数，说明了要传递给下一个视图的参数。


# 删除老index，detail和results 视图，并使用Django的通用视图代替。（其实不删除也行，因为方法名称变了，调用不到它们了）
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'  # 指定传入模版的context对象的变量名，也就是为列表重新命名。

    # 因为这是父类是ListView，所以可以直接写 model = Question ，获取所有的Question实例，封装称列表。这样就不需要get_queryset(self)方法了。

    def get_queryset(self):  # 这个函数，将会获取查询到的列表集，并把结果返回给 context对象。
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    # get_queryset(self)方法与context_object_name变量，通常都是配合使用的。
    # 以上方法会在类视图调用as_view()后自动调用。


class DetailView(generic.DetailView):
    model = Question
    # 因为父类是DetailView，所以 model = Question ，获取的是具体对应的 model对象。
    # context_object_name不需要写，因为context_object_name默认为是model的小写变量，即question，模版上直接用question就行了。
    template_name = 'polls/detail.html'

    def get_queryset(self):#这个函数，将会获取查询到的列表集（实际上只有一个实例），并把结果返回给context对象的变量名（即model，Question对象）。
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())    # 对实例进行过滤，只获取过去的问题。



class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
'''
这里使用两个通用视图（其实有多种通用视图）： ListView和 DetailView。这两个视图分别提取了“显示对象列表”和“显示特定类型对象的详细信息页面”的概念。
1.每个通用视图都需要知道它将采取什么样的模式。这是使用model属性提供的。
2.DetailView通用视图预计从URL中捕获的主键值被调用 "pk"，所以我们已经改变question_id，以pk用于通用视图。

DetailView默认使用一个叫做<app name>/<model name>_detail.html的模版，但是我们可以使用template_name这个属性来指定Django需要加载的模版。
ListView同理。

我的个人理解：
在URL路径中，index没有出现pk，id等关键字，也就不需要model，用ListView就行了。且，ListView主要用于获取某个model列表。
而detail和results等的URL中，有pk这种关键字，必须指定model，否则关键字就无效了，用DetailView。且，DetailView主要用于获取某单个model对象。

'''


class addView(generic.ListView):
    template_name = 'polls/add.html'
    model = Question


class questionView(generic.ListView):
    template_name = 'polls/question.html'
    context_object_name = 'latest_question_list'  # 指定传入模版的context对象的变量名，也就是为列表重新命名。

    def get_queryset(self):  # 这个函数，将会获取查询到的列表集，并把结果返回给 context对象。
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

polls/templates/polls/add.html
<!DOCTYPE html>

<html lang="en-us">
<head>
    <title>Add question | Django site admin</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css"/>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css"/>


    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <script type="text/javascript" src="/static/admin/js/calendar.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/DateTimeShortcuts.js"></script>
    <script type="text/javascript" src="/static/admin/js/collapse.js"></script>
    <script type="text/javascript" src="/static/admin/js/inlines.js"></script>

    <meta name="robots" content="NONE,NOARCHIVE"/>
</head>


<body class=" app-polls model-question change-form"
      data-admin-utc-offset="0">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

            <h1 id="site-name"><a href="/admin/">Polls Administration</a></h1>

        </div>


        <div id="user-tools">

            Welcome,
            <strong>admin</strong>.


            <a href="/">View site</a> /


            <a href="/admin/password_change/">Change password</a> /

            <a href="/admin/logout/">Log out</a>

        </div>


    </div>
    <!-- END Header -->

    <div class="breadcrumbs">
        <a href="/admin/">Home</a>
        &rsaquo; <a href="/admin/polls/">Polls</a>
        &rsaquo; <a href="/admin/polls/question/">Questions</a>
        &rsaquo; Add question
    </div>


    <!-- Content -->
    <div id="content" class="colM">

        <h1>Add question</h1>
        <div id="content-main">


            <form enctype="multipart/form-data" action="" method="post" id="question_form" novalidate><input
                    type='hidden' name='csrfmiddlewaretoken'
                    value='JW61UojBK5L7ju41QYVnS6j6XxwVXrx2Uirp3CZRDdIiKCJFAxyfIzGt0ROAXLfI'/>
                <div>


                    <fieldset class="module aligned ">


                        <div class="form-row field-question_text">


                            <div>


                                <label class="required" for="id_question_text">Question text:</label>

                                <input type="text" name="question_text" class="vTextField" maxlength="200" required
                                       id="id_question_text"/>


                            </div>

                        </div>

                    </fieldset>


                    <fieldset class="module aligned collapse">
                        <h2>Date information</h2>


                        <div class="form-row field-pub_date">


                            <div>


                                <label class="required" for="id_pub_date_0">Date published:</label>

                                <p class="datetime">
                                    Date: <input type="text" name="pub_date_0" class="vDateField" size="10" required
                                                 id="id_pub_date_0"/>

                                    <br/>
                                    Time: <input type="text" name="pub_date_1" class="vTimeField" size="8" required
                                                 id="id_pub_date_1"/>


                                </p>


                            </div>

                        </div>

                    </fieldset>


                    <div class="js-inline-admin-formset inline-group" id="choice_set-group"
                         data-inline-type="tabular"
                         data-inline-formset="{&quot;name&quot;: &quot;#choice_set&quot;, &quot;options&quot;: {&quot;prefix&quot;: &quot;choice_set&quot;, &quot;addText&quot;: &quot;Add another Choice&quot;, &quot;deleteText&quot;: &quot;Remove&quot;}}">
                        <div class="tabular inline-related last-related">
                            <input type="hidden" name="choice_set-TOTAL_FORMS" value="3"
                                   id="id_choice_set-TOTAL_FORMS"/><input type="hidden" name="choice_set-INITIAL_FORMS"
                                                                          value="0"
                                                                          id="id_choice_set-INITIAL_FORMS"/><input
                                type="hidden" name="choice_set-MIN_NUM_FORMS" value="0"
                                id="id_choice_set-MIN_NUM_FORMS"/><input type="hidden" name="choice_set-MAX_NUM_FORMS"
                                                                         value="1000" id="id_choice_set-MAX_NUM_FORMS"/>
                            <fieldset class="module ">
                                <h2>Choices</h2>

                                <table>
                                    <thead>
                                    <tr>
                                        <th class="original"></th>


                                        <th class="required">Choice text

                                        </th>


                                        <th class="required">Votes

                                        </th>


                                        <th>Delete?</th>
                                    </tr>
                                    </thead>

                                    <tbody>


                                    <tr class="form-row row1 "
                                        id="choice_set-0">
                                        <td class="original">

                                            <input type="hidden" name="choice_set-0-id" id="id_choice_set-0-id"/>
                                            <input type="hidden" name="choice_set-0-question"
                                                   id="id_choice_set-0-question"/>

                                        </td>


                                        <td class="field-choice_text">


                                            <input type="text" name="choice_set-0-choice_text" class="vTextField"
                                                   maxlength="200" id="id_choice_set-0-choice_text"/>

                                        </td>


                                        <td class="field-votes">


                                            <input type="number" name="choice_set-0-votes" value="0"
                                                   class="vIntegerField" id="id_choice_set-0-votes"/>

                                        </td>


                                        <td class="delete"></td>

                                    </tr>


                                    <tr class="form-row row2 "
                                        id="choice_set-1">
                                        <td class="original">

                                            <input type="hidden" name="choice_set-1-id" id="id_choice_set-1-id"/>
                                            <input type="hidden" name="choice_set-1-question"
                                                   id="id_choice_set-1-question"/>

                                        </td>


                                        <td class="field-choice_text">


                                            <input type="text" name="choice_set-1-choice_text" class="vTextField"
                                                   maxlength="200" id="id_choice_set-1-choice_text"/>

                                        </td>


                                        <td class="field-votes">


                                            <input type="number" name="choice_set-1-votes" value="0"
                                                   class="vIntegerField" id="id_choice_set-1-votes"/>

                                        </td>


                                        <td class="delete"></td>

                                    </tr>


                                    <tr class="form-row row1 "
                                        id="choice_set-2">
                                        <td class="original">

                                            <input type="hidden" name="choice_set-2-id" id="id_choice_set-2-id"/>
                                            <input type="hidden" name="choice_set-2-question"
                                                   id="id_choice_set-2-question"/>

                                        </td>


                                        <td class="field-choice_text">


                                            <input type="text" name="choice_set-2-choice_text" class="vTextField"
                                                   maxlength="200" id="id_choice_set-2-choice_text"/>

                                        </td>


                                        <td class="field-votes">


                                            <input type="number" name="choice_set-2-votes" value="0"
                                                   class="vIntegerField" id="id_choice_set-2-votes"/>

                                        </td>


                                        <td class="delete"></td>

                                    </tr>


                                    <tr class="form-row row2  empty-form"
                                        id="choice_set-empty">
                                        <td class="original">

                                            <input type="hidden" name="choice_set-__prefix__-id"
                                                   id="id_choice_set-__prefix__-id"/>
                                            <input type="hidden" name="choice_set-__prefix__-question"
                                                   id="id_choice_set-__prefix__-question"/>

                                        </td>


                                        <td class="field-choice_text">


                                            <input type="text" name="choice_set-__prefix__-choice_text"
                                                   class="vTextField" maxlength="200"
                                                   id="id_choice_set-__prefix__-choice_text"/>

                                        </td>


                                        <td class="field-votes">


                                            <input type="number" name="choice_set-__prefix__-votes" value="0"
                                                   class="vIntegerField" id="id_choice_set-__prefix__-votes"/>

                                        </td>


                                        <td class="delete"></td>

                                    </tr>

                                    </tbody>
                                </table>
                            </fieldset>
                        </div>
                    </div>


                    <div class="submit-row">
                        <input type="submit" value="Save" class="default" name="_save"/>


                        <input type="submit" value="Save and add another" name="_addanother"/>
                        <input type="submit" value="Save and continue editing" name="_continue"/>
                    </div>


                    <script type="text/javascript"
                            id="django-admin-form-add-constants"
                            src="/static/admin/js/change_form.js"

                            data-model-name="question"
                    >
                    </script>


                    <script type="text/javascript"
                            id="django-admin-prepopulated-fields-constants"
                            src="/static/admin/js/prepopulate_init.js"
                            data-prepopulated-fields="[]">
                    </script>


                </div>
            </form>
        </div>


        <br class="clear"/>
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>


</body>
</html>